services:
  - type: web
    name: farmacia-bot-telegram
    env: python
    plan: free          # <- usa instancia gratuita para evitar pedir tarjeta
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram-pharmacy-bot.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
